apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: flux
    spec:
      serviceAccountName: flux
      volumes:
        - name: kubedir
          configMap:
            name: flux-kube-config
      containers:
        - name: flux
          image: "weaveworks/flux:1.13.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          volumeMounts:
            - name: kubedir
              mountPath: /root/.kubectl
          env:
            - name: KUBECONFIG
              value: /root/.kubectl/kubeconfig.yaml
          args:
            - --memcached-hostname=flux-memcached.flux-system
            - --memcached-service=
            - --git-poll-interval=5m
            - --sync-interval=5m
            - --git-url=git@github.com:weaveworks/flux-get-started
            - --git-branch=master
            - --git-path=
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
