apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --memcached-hostname=flux-memcached.flux-master
            - --memcached-service=
            - --git-url=git@github.com:skleinjung/cluster-forge.git
            - --git-branch=master
            - --git-path=blueprints/e2etest/workloads/test-namespace
            - --git-poll-interval=1m
            - --sync-interval=1m
            - --registry-poll-interval=1m
            - --registry-rps=200
            - --registry-burst=125
            - --registry-trace=false