apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
      labels:
        app: flux
    spec:
      serviceAccountName: flux
      volumes:
        - name: flux-git-deploy
          secret:
            secretName: flux-git-deploy
            defaultMode: 0400
        - name: git-keygen
          emptyDir:
            medium: Memory
      containers:
        - name: flux
          image: "weaveworks/flux:1.14.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          volumeMounts:
            - name: flux-git-deploy
              mountPath: /etc/fluxd/ssh
              readOnly: true
            - name: git-keygen
              mountPath: /var/fluxd/keygen
          args:
            - --manifest-generation=true
            - --memcached-hostname=flux-memcached.bootstrap
            - --memcached-service=flux-memcached
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-timeout=20s
            - --git-set-author=false
            - --registry-rps=200
            - --registry-burst=125
            - --registry-trace=false
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 64Mi
