---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux
subjects:
  - name: flux
    kind: ServiceAccount
